language: node_js
node_js:
  - "node"
  - "lts/carbon"
  - "lts/dubnium"
script:
  - yarn lint
  - yarn test:unit
before_deploy:
  - yarn build
deploy:
  skip_cleanup: true
  provider: surge
  project: ./dist/
